### ISSUE TITLE
Bad cache entries trigger exception on v1.8.0

### ISSUE THREAD

**Issue by roberttheiv** [rtomayko/rack-cache#155] opened 2018-09-04 23:52 UTC
This change:

https://github.com/rtomayko/rack-cache/compare/v1.7.2...v1.8.0

Introduced the `purge` call if the cache entry is missing the `X-Content-Digest` entry. With this change, the "bad cache entry" will trigger a purge. Unfortunately the purge code is:

```
    def purge(key)
      raise NotImplementedError
    end
```

So if the cache fails in this way for any reason, it's going to throw an error instead of serving the response like it did before (by returning `nil` as a result of the bad cache entry). We have run into this on our production servers with some assets randomly ending up with bad cache values. It's not caught by the test because the test mocks `purge` to make sure it is called.

The fix would be to revert the change or correctly implement purge.

**Comment by grosser** [comment] 2018-09-05 01:40
I'd love to not revert and implement purge instead, can you make a PR for that ?
... another alternative would be to do a noop purge ... but that feels kinda wrong too

**Comment by grosser** [comment] 2018-09-05 01:40
@randallreedjr

**Comment by randallreedjr** [comment] 2018-09-05 01:49
I'm a little confused by this. The code cited by @roberttheiv is in the base Metastore class. It is not intended to be implemented in this class, but is handled in the subclasses. For example, the `Heap` metastore implements `purge` as follows:
```
def purge(key)
  @hash.delete(key)
  nil
end
```
I guess I would ask to see exactly what the exception message says.

**Comment by roberttheiv** [comment] 2018-09-28 00:43
@grosser @randallreedjr sorry for the delayed response. I accidentally had GitHub notifications turned off.

The error message was "NotImplementedError" raised from the pure line in question. The full stack trace is here:

```
Puma caught this error: NotImplementedError (NotImplementedError)
/home/<user>/.rbenv/gems/rack-cache-1.8.0/lib/rack/cache/meta_store.rb:179:in `purge'
/home/<user>/.rbenv/gems/rack-cache-1.8.0/lib/rack/cache/meta_store.rb:46:in `lookup'
/home/<user>/.rbenv/gems/rack-cache-1.8.0/lib/rack/cache/context.rb:173:in `lookup'
/home/<user>/.rbenv/gems/rack-cache-1.8.0/lib/rack/cache/context.rb:66:in `call!'
/home/<user>/.rbenv/gems/rack-cache-1.8.0/lib/rack/cache/context.rb:51:in `call'
/<app_dir>/lib/middlewares/our_proxy.rb:22:in `call'
/home/<user>/.rbenv/gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
/home/<user>/.rbenv/gems/railties-3.2.22/lib/rails/engine.rb:484:in `call'
/home/<user>/.rbenv/gems/railties-3.2.22/lib/rails/application.rb:231:in `call'
/home/<user>/.rbenv/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/<user>/.rbenv/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/home/<user>/.rbenv/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/home/<user>/.rbenv/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/home/<user>/.rbenv/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/home/<user>/.rbenv/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `call'
/home/<user>/.rbenv/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

I've removed references to our application. The `our_proxy.rb` here is some rack middleware we use, but in these cases it was just a pass-through, doing nothing. As you can see, we are using puma and rails 3.2 but as far as I know that shouldn't affect this.

**Comment by randallreedjr** [comment] 2018-09-30 01:18
@roberttheiv Which kind of meta store are you using?

**Comment by grosser** [comment] 2018-09-30 16:38
This was kind of a bug that is now fixed, which causes trouble for a small subset of users.
I don't think bumping to 2.0 will help much either since the problem is more that the error is hidden in an edge-case that few will see during testing.
So the better way to improve this would be to either:
 - ignore (make default nil) <-> no more breaking change
 - warn (make default warn or warn on initialize)
 - raise on initialize

**Comment by grosser** [comment] 2018-09-30 16:39
long term I think raise on initialize is best since it will alert users early that something needs to be done instead of hiding the issue longer ... thoughts ?

**Comment by roberttheiv** [comment] 2018-10-01 17:38
My preference would be to see this default to nil and warn on initialize. We implicitly depend on this gem through Rails 3.2 with apparently doesn't include a proper implementation of the meta_store with a purge operation.

I checked the dependency tree and it depends on `rack-cache ~> 1.2` according to my Gemfile.lock. Thus I'd prefer one of the first two options and perhaps later implement raise on initialize as breaking change put in 2.0.

**Comment by grosser** [comment] 2018-10-02 02:29
Sounds good, can you make that into a PR ?

**Comment by roberttheiv** [comment] 2018-10-02 21:37
Will do

**Comment by medexdev** [comment] 2019-01-09 17:40
any update on this? I'm experiencing this issue in production.

**Comment by grosser** [comment] 2019-01-09 17:55
hot-fix is to monkey-patch in the purge call to noop
shady fix would be to downgrade
best would be to implement PR with change as discussed here

**Comment by medexdev** [comment] 2019-01-09 19:34
Thanks. downgraded to 1.7.2 for now.

**Comment by tr00gle** [comment] 2019-02-19 20:36
I just came across this same error in our production codebase. Has the aforementioned PR been made and/or merged yet?

**Comment by roberttheiv** [comment] 2019-02-19 22:56
I forgot about implementing this PR. I will do that this week if I can get it squeezed in. Sorry for the delay.

**Comment by grosser** [comment] 2019-02-26 16:49
1.9.0
🎉 @roberttheiv

**Closed by grosser** 2019-02-26 16:49 UTC

**Comment by tr00gle** [comment] 2019-03-19 20:39
@roberttheiv Had an issue with this gem that I assume was solved with your PR, but I'm having some trouble coming up with an appropriate way to test it. Any suggestions?

**Comment by roberttheiv** [comment] 2019-03-19 21:11
@tr00gle Not sure the best way. We haven't put this gem through our release cycle quite yet, but the bug was a very rare occurrence for us. My test would tend to be to modify the `X-Content-Digest` manually in a request, using curl or something like that. Verify with & without. May be difficult depending on your application setup and it probably needs to be a production-like environment with the same caching setup.
